apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: dev
  labels:
    app: myapp
    type: frontend
spec:
  replicas: 3
  template:
    metadata:
      name: myreplicaset
      labels:
        app: myapp
    spec:
      containers:
      - name: mywebserver
        image: aamirs/radical-private-repo:v1.0
        command: [ "/usr/sbin/httpd", "-D", "FOREGROUND" ]
        volumeMounts:
          - name: efs-pv
            mountPath: "/var/www/html"
      imagePullSecrets:
      - name: mydocker
      volumes:
        - name: efs-pv
          persistentVolumeClaim:
            claimName: efs-claim

  selector:
    matchLabels:
      app: myapp