apiVersion: v1
kind: Secret
metadata:
  name: my-docker-hub-secret
  namespace: dev
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIllXRnRhWEp6T2twdmNtUmhia0F5TURFNE1BPT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
