---
- name: This sets up a Docker server
  hosts: testvm-dev
  remote_user: ec2-user
  become: true
  become_method: sudo
  vars_files:
       - docker_token.yml
  vars:
    vol: /tmp/myefs/docker_volume/
    IMAGE: "{{ lookup('env', 'IMAGE') }}"
    WORKSPACE: "{{ lookup('env', 'WORKSPACE') }}"
    DockerHub_repo: "{{ lookup('env', 'DockerHub_repo') }}"
    VER: "{{ lookup('env', 'VER') }}"

  tasks:
  - name: set fact here
    set_fact:
      random_number: "{{ 100 | random }}"
    run_once: yes

  - name: Installing Docker
    yum:
      name: docker
      state: present

  - name: Installing Git
    yum:
      name: git
      state: present

  - name: Start Docker Service
    service:
      name: docker
      state: started

  - name: Enable Docker Service
    service:
      name: docker
      enabled: yes

  - name: Creating test container
    command: "{{ item }}"
    with_items:
    - docker run -itd  --name=test_machine320"{{ random_number }}" centos
    - docker run -itd --name=webserver320"{{ random_number }}" -p 320"{{ random_number }}":80 -v "{{ vol }}":/var/www/html/  {{ DockerHub_repo }}:{{ VER}}
    register: shell_result
  - debug:
      var: shell_result

  - name: Testing
    shell: host myip.opendns.com resolver1.opendns.com | grep address |  awk '{print $4}'
    register: shell_result
  - debug:
      msg: Testing URL is http://{{ shell_result.stdout }}:320{{ random_number }}/webapp/index_dev.jsp

  - name: Checking if the above link is working as expected
    ansible.builtin.raw: curl -kv http://{{ shell_result.stdout }}:320{{ random_number }}/webapp/index_dev.jsp
    register: url_check
  - debug:
      var: url_check


